name: deneme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^0.8.7
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  simple_barcode_scanner: ^0.0.8
  flutter_form_builder: ^9.2.1
  form_builder_extra_fields: ^10.1.0
  form_builder_image_picker: ^4.0.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/device/
    - assets/devices.json